# Generated by Django 4.1.1 on 2022-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('msg', models.TextField(verbose_name='Message')),
                ('app', models.CharField(max_length=100, verbose_name='App name')),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=7, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
            ],
        ),
    ]
