# Generated by Django 4.1.1 on 2022-09-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='status',
        ),
    ]
